### ISSUE TITLE
Add CHARGING_AMPS incl. yet unknown parameter name to README.md "Commands" table

### ISSUE THREAD

**Issue by frsteinb** [tdorssers/TeslaPy#36]
The new command CHARGING_AMPS obviously has to have a parameter to set the intended current. Does anybody know the name of this parameter and its value range (maybe, e.g. simply 5..16 for Model 3)? When it is known, it should be added to the according table in the Commands section of the README.md file.

**Comment by godkane1** [comment]
I would also find this useful.

**Comment by tdorssers** [comment]
This endpoint should become available with 2021.36 software, and that's pretty much everything I know about this.

**Comment by treynaer** [comment]
Hi, I have 2021.36 on my model 3 since last Friday. I also can change the charge amps in the Telsa app. How can I assist?

**Comment by frsteinb** [comment]
Thank you very much for your assistance!

If you are able to setup TeslaPy, including the authentication steps and execute a command like the one from the README.md file for your vehicle:

`python cli.py -e elon@tesla.com -w -a ACTUATE_TRUNK -k which_trunk=front`

then you could start trying to adjust the amps by a similar command. When it does not return an error code, then you could check from the Tesla App (or in the car) whether it really succeeded and modified the charging amps. You could try (assuming amps are not currently set to exactly 10 A):

`python cli.py -e elon@tesla.com -w -a CHARGING_AMPS -k amps=10`
`python cli.py -e elon@tesla.com -w -a CHARGING_AMPS -k charging_amps=10`
`python cli.py -e elon@tesla.com -w -a CHARGING_AMPS -k chargingamps=10`
`python cli.py -e elon@tesla.com -w -a CHARGING_AMPS -k current=10`
...

**Comment by godkane1** [comment]
Try set_charging_amps instead of CHARGING_AMPS.

**Comment by dmaunder** [comment]
Same.

vehicles[0].command('SET_CHARGING_AMPS', amps=10)

ValueError: Unknown endpoint name SET_CHARGING_AMPS

**Comment by treynaer** [comment]
No luck yet with the SSL Proxy. In the app you see the current AMPS and have arrows up and down to change.

**Comment by tdorssers** [comment]
Added to the table, see commit b217a4e.
@dmaunder can you investigate SCHEDULED_CHARGING and SCHEDULED_DEPARTURE as well?

**Comment by dmaunder** [comment]
> @dmaunder can you investigate SCHEDULED_CHARGING and SCHEDULED_DEPARTURE as well?

Ill have a look on Thursday if I get time

**Comment by themonomers** [comment]
Through trial and error, I found the payload to pass in the POST for set_scheduled_charging is:

`payload = {
  'enable': 'True',
  'time': <time>
}`

where `<time>` is the number of minutes so if you want 6:00AM local time, then `<time>` would be 360.

**Comment by themonomers** [comment]
> Thanks @themonomers, what about SCHEDULED_DEPARTURE?

No luck yet.  Still working on it.

**Comment by themonomers** [comment]
> > Thanks @themonomers, what about SCHEDULED_DEPARTURE?
> 
> No luck yet. Still working on it; I have it half-working.

Here's where I am on set_scheduled_departure.  The payload currently looks like this:

`    payload = {
      'enable': 'True',
      'departure_time': <time>,
      'preconditioning_enabled': 'False',
      'preconditioning_times': 'weekdays'
      'off_peak_charging_enabled': 'True',
      'off_peak_charging_times': 'weekdays',
      'off_peak_hours_end_time': (6 * 60)
    }
`

What works:  `enable`, `departure_time`, `preconditioning_enabled`, and `off_peak_charging_enabled`.  These 4 attributes correctly modify the settings and reflect the same in the mobile app.  The other ones I can't seem to figure out.  I've tried varied names for the attributes and even tried some nested structures.  

Additionally, perhaps it's a defect or my lack of understanding but in the mobile app there's no "enable" toggle for departure mode like there is for scheduled charging mode.  When you toggle the enable for the scheduled charging in the mobile app, when it's plugged in it will show a message like "Charging will start at 5:00 AM" in the charging section but not for departure mode UNLESS you also toggle on Off-peak Charge.  Only if you toggle Off-peak Charge in the mobile app will it show a message in the charging section about the departure time.  When using the API, I can't get it to do that because I'm not passing the correct attribute for `off_peak_hours_end_time` and it defaults to 12:00 AM, despite having toggled the value for `off_peak_charging_enabled`.  If I manually update the `off_peak_hours_end_time` from the mobile app, it will correctly show the message in the charging section.

**Comment by tdorssers** [comment]
Excellent job, thanks!
